spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    open:
      url: jdbc:mysql://localhost:3306/open?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver